FANCY ARRAY

In [30]:
import numpy as np

In [31]:
a = np.array([1, 7, 3, 10, 30, 45])
a

array([ 1,  7,  3, 10, 30, 45])

In [32]:
b = a[1:4] # b è una view di a

print(a)
print(b)
print(b.base is a) # b è un array che è basato su a

[ 1  7  3 10 30 45]
[ 7  3 10]
True


In [37]:
c = a[:]

print(c)
print(c.base is a)

[ 1  7  3 10 30 45]
True


In [36]:
b = a[[True, False, True, False, False, True]]
print(b)

[ 1  3 45]


In [35]:
b = a[[5, 4, 1]]
print(b)

[45 30  7]


In [42]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(mat[:, 2]) # terza colonna
print(mat[1, :]) # seconda riga

[3 6 9]
[4 5 6]


In [47]:
terza_colonna = mat[:, 2]
print(terza_colonna)

[3 6 9]


In [48]:
terza_colonna[...] = 11
print(terza_colonna)
print(mat)

[11 11 11]
[[ 1  2 11]
 [ 4  5 11]
 [ 7  8 11]]


In [55]:
mat_bit = np.random.randint(0, 2, size = (10, 10))
print(mat_bit)

[[0 0 1 0 0 1 1 1 0 1]
 [0 1 1 1 1 0 1 0 1 1]
 [1 1 0 1 0 0 0 1 1 1]
 [1 1 0 0 1 0 1 1 0 1]
 [0 1 0 0 0 0 0 1 0 1]
 [1 1 1 1 0 0 0 1 1 1]
 [0 1 1 0 0 1 0 0 1 0]
 [1 0 0 0 0 1 0 1 0 1]
 [0 1 0 1 0 0 1 0 0 1]
 [1 0 1 1 0 1 0 1 0 1]]


In [56]:
mat_bit[0, :] = 0
mat_bit[9, :] = 0
mat_bit[:, 0] = 0
mat_bit[:, 9] = 0

print(mat_bit)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 1 0 1 0]
 [0 1 0 1 0 0 0 1 1 0]
 [0 1 0 0 1 0 1 1 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 1 1 1 0 0 0 1 1 0]
 [0 1 1 0 0 1 0 0 1 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 1 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


ESEMPIO

In [25]:
dado_Alice = np.random.randint(1, 7, 10)
dado_Bob = np.random.randint(1, 7, 10)

print(f"{dado_Alice} - {dado_Bob}")

[2 4 3 6 3 5 3 1 2 2] - [2 4 2 2 2 6 5 5 5 6]


In [26]:
punteggi_vittoria_Alice = dado_Alice[dado_Alice > dado_Bob]
print(punteggi_vittoria_Alice)

[3 6 3]


In [27]:
punteggi_vittoria_Alice.base is dado_Bob

False