In [12]:
import numpy as np

In [13]:
# funzione dei numeri primi
def isprime(n): 
    for a in range(2, int(np.sqrt(n)) + 1):
        if n%a == 0:
            return False
    return True

In [14]:
isprime(24)

False

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 2, 2])

In [11]:
# tutte le operazioni matematiche agiscono sui singoli elemnti negli array, elemtento per elemento
print(a + b) # somma elemento per elemento
print(a * b) # moltiplica elemento per elemento
print(a**2) # eleva al quadrato ogni valore di a

[3 4 5 6]
[2 4 6 8]
[ 1  4  9 16]


In [16]:
c = np.arange(2, 30)
c

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
isprime_v = np.vectorize(isprime)

In [22]:
print(isprime_v(c))

c[isprime_v(c)] # stampa i numeri primi dell'array c

[ True  True False  True False  True False False False  True False  True
 False False False  True False  True False False False  True False False
 False False False  True]


array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [23]:
np.pi # pigreco

3.141592653589793

In [5]:
np.concatenate((a, b)) # concatena i 2 array che gli vengono passati come tupla

array([1, 2, 3, 4, 2, 2, 2, 2])