In [14]:
import numpy as np

## Da liste ad array con numpy

In [15]:
lista = [1, 2, 3, 4, 5, 6]

lista_array = np.array(lista)
lista_array

array([1, 2, 3, 4, 5, 6])

## array di 0 e array di 1

In [16]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros((5, 10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.ones((5, 10), dtype = int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## numpy random

### - random.uniform

In [19]:
np.random.uniform() # con uniform si trovano valori da 0 a 1

0.5977373695475234

In [20]:
np.random.uniform(size = 100) # si generea un array di 100 elementi con valori tra 0 e 1

array([0.69079193, 0.93027483, 0.5487431 , 0.4577048 , 0.72399694,
       0.8874777 , 0.93229554, 0.04520423, 0.40172983, 0.42561241,
       0.08870448, 0.2306272 , 0.70737758, 0.70444117, 0.30945359,
       0.89007927, 0.18035597, 0.18424124, 0.01167716, 0.41148443,
       0.60543353, 0.73933118, 0.52283691, 0.50868902, 0.08021266,
       0.10572695, 0.52888393, 0.56400549, 0.11888061, 0.81341898,
       0.74296063, 0.28691926, 0.94468969, 0.4638422 , 0.30524069,
       0.87780449, 0.82675189, 0.5227451 , 0.65991516, 0.60167228,
       0.14416828, 0.64613927, 0.39327494, 0.87442719, 0.10949059,
       0.97888184, 0.92733335, 0.43378704, 0.62664807, 0.21164707,
       0.90997402, 0.49050675, 0.62314328, 0.08137639, 0.94105184,
       0.33435263, 0.10740898, 0.46032057, 0.59317126, 0.56757981,
       0.18086031, 0.95379386, 0.99713734, 0.31622314, 0.5430398 ,
       0.44377789, 0.97192733, 0.48837177, 0.90084529, 0.41762293,
       0.64706521, 0.82490161, 0.26867054, 0.05590839, 0.49200

### - random.normal

In [22]:
np.random.normal()

-0.22850751378709502

In [23]:
np.random.normal(size = 10)

array([ 0.45677678, -0.16938614,  0.67983861, -0.86174031,  0.30248604,
        0.89312599, -0.16157942, -1.32056145,  1.2893344 ,  0.99447703])

In [25]:
np.random.normal(loc = 5, scale = 1, size = 100)

array([6.74791415, 2.70659028, 4.43537001, 4.09981189, 4.69375639,
       2.84471101, 3.11982888, 6.90180423, 4.64650546, 4.66975667,
       6.92064699, 5.43984602, 2.69732272, 5.35439972, 6.27561568,
       5.59788741, 6.02004786, 4.27304897, 6.53741952, 5.97230627,
       4.20197354, 4.66630291, 4.02924408, 6.40616781, 4.25738594,
       6.02472341, 5.17656553, 5.74489561, 5.03071567, 5.306388  ,
       5.716058  , 3.58013063, 4.60848904, 6.09830324, 5.35778136,
       6.37368927, 6.13155681, 4.72861203, 5.4841169 , 4.80054799,
       4.55214327, 3.73456006, 4.99776528, 7.06884449, 2.84704163,
       4.29980942, 3.04912408, 5.67074173, 5.58965161, 3.33349825,
       4.0818822 , 5.43840496, 5.07770777, 5.0861023 , 5.17852661,
       6.078788  , 3.75127808, 7.07954335, 5.25892469, 6.31326169,
       6.04281847, 6.84894702, 4.62412426, 5.8174338 , 3.40551461,
       4.38933958, 4.62670809, 4.02470744, 4.56404049, 5.02784133,
       4.56504949, 5.71420388, 6.21054361, 3.67101674, 4.77480

### - random.random_integers

In [28]:
np.random.random_integers(low = 0, high = 90, size = 100) # interi da 0 a 90, in un array da 100 elementi

<ipython-input-28-4de87bc326dc>:1: DeprecationWarning: This function is deprecated. Please call randint(0, 90 + 1) instead
  np.random.random_integers(low = 0, high = 90, size = 100)


array([30, 38, 35, 26, 80, 25, 61, 86, 61, 44, 21, 43, 89, 79, 70, 43, 25,
       33, 17, 57,  0, 73, 67, 37, 38, 28, 26, 17, 34, 58, 69, 25, 64, 24,
       71, 75, 19, 79, 76,  0, 85, 27, 33, 18, 54, 15, 62, 71,  4, 50, 37,
       66, 54, 90, 72, 82, 61, 78, 31, 88,  1,  5, 53, 29, 84, 60,  3, 62,
       51, 60, 27, 84, 11, 61, 46, 18,  6, 20, 73,  2, 85, 37, 38, 28, 45,
       39, 58,  2, 68, 19, 80, 29, 43, 26, 46, 85, 18,  3, 60, 77])

### - random.choise

In [33]:
np.random.choice(["Testa", "Croce"], size = 10) # scelta tra "Testa" e "Croce", in un array di 10 elementi 

array(['Testa', 'Testa', 'Croce', 'Croce', 'Croce', 'Croce', 'Testa',
       'Croce', 'Testa', 'Testa'], dtype='<U5')

## MATRICI

In [46]:
matrice = np.random.uniform(size = (4, 5))
print(matrice)

[[0.05213581 0.99044847 0.9403662  0.18817322 0.55125633]
 [0.62731244 0.82380801 0.52042583 0.00739013 0.64408153]
 [0.34283007 0.80341952 0.70113802 0.89508324 0.36013809]
 [0.22058479 0.4878127  0.27814865 0.55106176 0.12539226]]


In [47]:
print(np.shape(matrice))
print(np.size(matrice))

(4, 5)
20


In [48]:
vettore = np.array([1, 2, 3, 4, 5])

print(np.shape(vettore))
print(np.size(vettore)) 

(5,)
5


In [49]:
matrice

array([[0.05213581, 0.99044847, 0.9403662 , 0.18817322, 0.55125633],
       [0.62731244, 0.82380801, 0.52042583, 0.00739013, 0.64408153],
       [0.34283007, 0.80341952, 0.70113802, 0.89508324, 0.36013809],
       [0.22058479, 0.4878127 , 0.27814865, 0.55106176, 0.12539226]])

In [50]:
matrice1 = np.ravel(matrice) # conpatta la matrice su un unica riga

print(matrice1)

[0.05213581 0.99044847 0.9403662  0.18817322 0.55125633 0.62731244
 0.82380801 0.52042583 0.00739013 0.64408153 0.34283007 0.80341952
 0.70113802 0.89508324 0.36013809 0.22058479 0.4878127  0.27814865
 0.55106176 0.12539226]


In [51]:
matrice.reshape(10, 2) 
# riformula la matrice secondo il nuovo ordine, il numero di elementi deve essere uguale al numeor elementi originari


array([[0.05213581, 0.99044847],
       [0.9403662 , 0.18817322],
       [0.55125633, 0.62731244],
       [0.82380801, 0.52042583],
       [0.00739013, 0.64408153],
       [0.34283007, 0.80341952],
       [0.70113802, 0.89508324],
       [0.36013809, 0.22058479],
       [0.4878127 , 0.27814865],
       [0.55106176, 0.12539226]])

In [53]:
np.transpose(matrice)

array([[0.05213581, 0.62731244, 0.34283007, 0.22058479],
       [0.99044847, 0.82380801, 0.80341952, 0.4878127 ],
       [0.9403662 , 0.52042583, 0.70113802, 0.27814865],
       [0.18817322, 0.00739013, 0.89508324, 0.55106176],
       [0.55125633, 0.64408153, 0.36013809, 0.12539226]])

# Esercizio

In [87]:
# quante volte esce il numero 6 se tiro il dado 10'000 volte
lanci_dado = np.random.randint(1, 7, 10000)
print(lanci_dado)

[5 6 6 ... 3 3 3]


In [88]:
np.count_nonzero(lanci_dado == 6) / 10000 # numero di volte uscito il 6 in 10000 lanci, in probabilità

0.168

In [86]:
1 / 6 # calcolo teorico delle probabilità

0.16666666666666666

In [89]:
# se tiro un dado 10'000 volte, quante volte esce un numero >= 4
lanci_dado = np.random.randint(1, 7, 10000)
print(lanci_dado)

[6 3 4 ... 6 1 6]


In [93]:
np.count_nonzero(lanci_dado >= 4) / 10000 # numero di volte uscito il numero >= 4 in 10000 lanci, in probabilità

0.5062

In [94]:
3 / 6 # calcolo teorico

0.5

In [95]:
# quante volte esce il numero 6 se tiro 2 dadi 10'000 volte ciascuno
lanci_dado1 = np.random.randint(1, 7, 10000)
lanci_dado2 = np.random.randint(1, 7, 10000)

In [97]:
lanci_dado1 + lanci_dado2

array([ 9,  5,  8, ...,  7, 10,  3])

In [99]:
lanci_dado1 + lanci_dado2 > 6

array([ True, False,  True, ...,  True,  True, False])

In [100]:
np.count_nonzero(lanci_dado1 + lanci_dado2 > 6) / 10000

0.5885