In [3]:
import numpy as np

ESERCIZIO 1

In [24]:
mat_bin = np.zeros(shape = (8, 8))

In [26]:
for r in range(8):
    for c in range(8):
        if r%2 == 0:
            if c%2 == 1:
                mat_bin[r][c] = 1
            else:
                mat_bin[r][c] = 0
        else :
            if c%2 == 0:
                mat_bin[r][c] = 1
            else:
                mat_bin[r][c] = 0
print(mat_bin)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


ESERCIZIO 2

In [27]:
Z = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
L = []

In [28]:
for a in range(len(Z)-3):
    L.append((Z[a], Z[a+1], Z[a+2], Z[a+3]))

R = np.array(L, np.uint8)

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


ESERCIZIO 3

In [71]:
n_classe = int(input("Inserire il numero di compagni: "))

Inserire il numero di compagni: 3


In [72]:
minimo = float(np.random.randint(140, 150))
massimo = float(np.random.randint(190, 200))

scala = 10 # variazione di valori
centro = float(np.random.randint(minimo, massimo))

In [73]:
classe = np.random.normal(centro, scala, n_classe)

classe

array([178.27482792, 153.36123181, 160.66515993])

ESERCIZIO 4

In [54]:
mat_cen = np.random.randint(0, 1, size = (10, 10))

lung_arr = len(mat_cen)
range_for = int(lung_arr / 2)

mat_min = 0
mat_max = lung_arr - 1

In [55]:
for a in range(range_for + 1):
    mat_cen[mat_min, mat_min : mat_max] = a + 1 # alto
    mat_cen[mat_max, mat_min : mat_max] = a + 1 # basso
    mat_cen[mat_min : mat_max, mat_min] = a + 1 # sinistra
    mat_cen[mat_min : mat_max, mat_max] = a + 1 # destra
    
    if a > 0: 
        mat_cen[-a, -a] = a
    
    mat_min += 1
    mat_max -= 1

print(mat_cen)

[[1 1 1 1 1 1 1 1 1 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 5 5 4 3 2 1]
 [1 2 3 4 4 4 4 3 2 1]
 [1 2 3 3 3 3 3 3 2 1]
 [1 2 2 2 2 2 2 2 2 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [56]:
"""
Altro modo del 4:
mat_cen[0, :] = 1
mat_cen[9, :] = 1
mat_cen[:, 0] = 1
mat_cen[:, 9] = 1

mat_cen[1, 1:8] = 2
mat_cen[8, 1:8] = 2
mat_cen[1:8, 1] = 2
mat_cen[1:8, 8] = 2

mat_cen[2, 2:7] = 3
mat_cen[7, 2:7] = 3
mat_cen[2:7, 2] = 3
mat_cen[2:7, 7] = 3

mat_cen[3, 3:6] = 4
mat_cen[6, 3:6] = 4
mat_cen[3:6, 3] = 4
mat_cen[3:6, 6] = 4

mat_cen[4, 4:5] = 5
mat_cen[5, 4:5] = 5
mat_cen[4:5, 4] = 5
mat_cen[4:5, 5] = 5
"""

'\nAltro modo del 4:\nmat_cen[0, :] = 1\nmat_cen[9, :] = 1\nmat_cen[:, 0] = 1\nmat_cen[:, 9] = 1\n\nmat_cen[1, 1:8] = 2\nmat_cen[8, 1:8] = 2\nmat_cen[1:8, 1] = 2\nmat_cen[1:8, 8] = 2\n\nmat_cen[2, 2:7] = 3\nmat_cen[7, 2:7] = 3\nmat_cen[2:7, 2] = 3\nmat_cen[2:7, 7] = 3\n\nmat_cen[3, 3:6] = 4\nmat_cen[6, 3:6] = 4\nmat_cen[3:6, 3] = 4\nmat_cen[3:6, 6] = 4\n\nmat_cen[4, 4:5] = 5\nmat_cen[5, 4:5] = 5\nmat_cen[4:5, 4] = 5\nmat_cen[4:5, 5] = 5\n'