In [11]:
import numpy as np
import uuid

BROADCAST

In [2]:
a = np.arange(0, 12) # array da 0 a 11
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
a + 5 # somma 5 a tutti i valori dell'array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [5]:
b = a.reshape((4, 3)) # riformazione del array
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
c = np.ones(3)*100
c

array([100., 100., 100.])

In [9]:
b + c # somma di riga per riga

array([[100., 101., 102.],
       [103., 104., 105.],
       [106., 107., 108.],
       [109., 110., 111.]])

Comandi magici

In [10]:
# sono comandi che cominciano o con % o %%
# %%timeit esegue la cella molte volte, e restituisce la media tra tutti in notazione standard

In [13]:
n_passeggeri = 2000000
temperature = np.random.normal(36.5, 0.25, n_passeggeri)
identificativi = np.array([str(uuid.uuid4()) for _ in range(n_passeggeri)])

In [14]:
identificativi

array(['e23257bf-a63a-48d2-b471-b7ef5e0f135d',
       '4d6ff7ed-482d-4d24-8511-98f58bc03279',
       'babf2670-6b41-4d5d-bd66-b203ad0f20c0', ...,
       '852607aa-e190-4f20-86e0-7f51b3163f31',
       '4ded3fdd-2e60-43a8-8fbe-16b900d6f388',
       '89d42aaf-1353-44fe-a7e7-0f73394927d0'], dtype='<U36')

In [17]:
%%timeit
contatore = np.count_nonzero(temperature > 37.5)

2.12 ms ± 32.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
